/* =========================================================
   answers.js — 中英双语答案库 + 话题识别
   ---------------------------------------------------------
   · 问题用什么语言问，就用什么语言回答（中文问 → 中文答）
   · 关键词库中英合并，中文问题也能正确分类
   · 英文答案里用 {…} 标记金色高亮；中文答案由程序自动
     高亮开头那句短语（宋体渲染）
   ========================================================= */

var TOPICS = {

  love: {
    label: "Love", icon: "💗",
    keys: [
      "love",
      "like",
      "likes",
      "crush",
      "dating",
      "date",
      "boyfriend",
      "girlfriend",
      "partner",
      "ex",
      "breakup",
      "break up",
      "broke up",
      "confess",
      "confession",
      "marry",
      "marriage",
      "relationship",
      "romance",
      "romantic",
      "valentine",
      "soulmate",
      "flirt",
      "together",
      "feelings",
      "text back",
      "talking to",
      "situationship",
      "him",
      "her",
      "喜欢",
      "爱",
      "暗恋",
      "表白",
      "告白",
      "追求",
      "心动",
      "男朋友",
      "女朋友",
      "男友",
      "女友",
      "对象",
      "恋爱",
      "分手",
      "复合",
      "挽回",
      "暧昧",
      "结婚",
      "婚姻",
      "相亲",
      "感情",
      "前任",
      "异地",
      "脱单",
      "单身",
      "缘分",
      "在一起",
      "忽冷忽热",
      "冷淡",
      "约会",
      "婚"
    ],
    en: [
      "Say it first. {The person you keep thinking about} has been waiting for a sign, and yours is the one they would notice.",
      "Give it three more weeks. {This connection} is warming up slowly, and rushing it now would break the spell.",
      "Yes — and the answer is nearer than you think. {Someone already in your everyday circle} looks at you a little differently.",
      "Reach out tonight. {One short, honest message} will do more than a perfectly crafted one sent next week.",
      "Let them come to you this time. {Your patience} is the very thing that will draw them closer.",
      "It is mutual. {The hesitation you keep sensing} is shyness, not disinterest.",
      "Plan something small together. {One ordinary shared afternoon} will tell you more than any long conversation.",
      "Be a little less available. {A little distance} reminds them what your presence actually feels like.",
      "Trust the pull you feel. {This one} is worth the risk of being honest.",
      "Say yes to the invitation. The next time they ask, {do not overthink it}.",
      "Not yet. {Their heart} is still sorting itself out, and pushing now would only close the door.",
      "Step back and watch. {The pattern you keep excusing} is the answer you have been avoiding.",
      "You are giving more than you are getting. {Name that imbalance out loud} before it hardens into resentment.",
      "Wait for actions, not words. {A promise with no date attached} is only a mood.",
      "Let this one go. {What you miss} is the version of them you hoped for, not the one who actually showed up.",
      "Distance and family are doing more damage than feelings. {The practical obstacle} is the real question here.",
      "Be careful of being someone's option. {Consistent effort} is the only proof worth accepting.",
      "Hold your boundary. {Saying no once} will tell you everything about how much you actually matter to them.",
      "Do not confuse comfort with love. {Familiarity} can feel like affection for months.",
      "Slow down. {Right now} is not the moment to make it official — give it one more season."
    ],
    zh: [
      "有戏。对方的注意力其实已经落在你身上了，只是还没找到开口的时机。",
      "会成。你主动迈出那一步，关系就会顺势往前推。",
      "这段感情有继续走下去的底子，别急着下结论。",
      "你担心的那件事，大概率不会发生，可以放心。",
      "对方对你有好感，只是表达比较含蓄，别用「他不够热情」来误判。",
      "复合是有机会的，但前提是先把当初分开的原因摊开说清楚。",
      "关系会往更稳定的方向走，你们正处在磨合之后的升温期。",
      "你是被喜欢的那一方，可以稍微放松一点。",
      "有新的缘分在靠近，可能来自你原本不太留意的圈子。",
      "现在适合表达心意，时机比你想象的好。",
      "这段关系能给你安全感，值得投入。",
      "会有一个明确的答案给你，不用再猜来猜去了。",
      "你们之间的默契比表面看起来更深，别被一时的冷淡吓退。",
      "对方的犹豫不是不喜欢，而是在权衡现实问题，给他一点时间。",
      "你的直觉是对的，这段感情值得再试一次。",
      "有转机。之前的误会会被解开。",
      "现在不是推进的好时机，对方的心还没定下来。",
      "你在这段关系里付出的比收到的多，这个失衡需要被看见。",
      "有第三方因素或现实阻力（家人、距离、工作），不是你们不够喜欢。",
      "对方的承诺要打个问号，先看行动再看话。",
      "复合的难度偏大，勉强在一起容易重蹈覆辙。",
      "你可能把「习惯」当成了「喜欢」，先分清楚。",
      "这段关系里的问题不会自己消失，需要有人先开口。",
      "对方态度模糊，是因为他也在两难，别替他做决定。",
      "你太用力了。抓得越紧，对方越想退。",
      "会有一次失望，但这不是终点，只是让你看清一些事。",
      "别为了不孤单而将就，这次的答案是「再等等」。",
      "你在回避一个已经很明显的事实。",
      "感情上的消耗大于滋养，你需要为自己设一条底线。",
      "短期内不会有明确答复，做好等待或放手的准备。",
      "表白成功的概率不高，建议先把关系处得更自然。",
      "旧的问题会再次浮现，不解决的话，换个人也会遇到。"
    ]
  },

  career: {
    label: "Work", icon: "💼",
    keys: [
      "job",
      "work",
      "career",
      "boss",
      "manager",
      "interview",
      "resume",
      "cv",
      "offer",
      "promotion",
      "raise",
      "salary",
      "quit",
      "resign",
      "colleague",
      "coworker",
      "project",
      "startup",
      "business",
      "team",
      "client",
      "deadline",
      "internship",
      "hired",
      "fired",
      "layoff",
      "meeting",
      "overtime",
      "workplace",
      "company",
      "role",
      "position",
      "apply for",
      "工作",
      "事业",
      "职场",
      "求职",
      "面试",
      "简历",
      "录用",
      "升职",
      "晋升",
      "加薪",
      "涨薪",
      "跳槽",
      "离职",
      "辞职",
      "老板",
      "领导",
      "同事",
      "项目",
      "创业",
      "副业",
      "试用期",
      "转正",
      "裁员",
      "绩效",
      "考核",
      "公司",
      "就业",
      "打工",
      "实习",
      "岗位",
      "职业"
    ],
    en: [
      "Apply anyway. {The role} is a better fit than the job description makes it sound.",
      "Speak up in the next meeting. {Your idea} is stronger than you are giving it credit for.",
      "Ask for the number first. {Your rate} has been quietly undervalued for a while now.",
      "Take the smaller, stranger project. {The odd opportunity} is where the real door opens.",
      "Yes to the change. {This move} looks like a detour and behaves like a shortcut.",
      "Find one senior person and ask them for twenty minutes. {The advice} will save you a year.",
      "Finish the boring part first. {The unglamorous groundwork} is what makes the rest land.",
      "Say yes to leading it. {The responsibility} is being handed to you because someone already trusts you.",
      "Send the follow-up. {The silence} is administrative, not personal.",
      "Negotiate once more. {There is room} and they are waiting to see if you will ask.",
      "Pause before signing. {One clause} is vaguer than it should be, and it will matter later.",
      "Do not resign this week. {The frustration} is real, but the timing is doing the damage.",
      "Lower the bet. {This project} is carrying more risk than the brief admits.",
      "Protect your calendar. {Being the person who always says yes} is why the good work never reaches you.",
      "Ask for it in writing. {Verbal promises} have a short shelf life in organisations.",
      "Stop polishing, start shipping. {The last ten percent} is costing you the whole opportunity.",
      "This environment has a ceiling. {What you are learning here} is close to finished.",
      "Avoid the politics. {The fight between the two camps} is not yours to win.",
      "Take the rest day. {Your exhaustion} is now a business risk, not a personal weakness.",
      "Hold the offer loosely. {This one} may fall through, and you should have a second line ready."
    ],
    zh: [
      "会有好消息，你投出去的努力正在被看见。",
      "这次机会能拿下，你的准备比你以为的充分。",
      "适合主动争取，上面的人对你的印象不差。",
      "工作会往更稳定的方向走，短期辛苦是值得的。",
      "你的能力在这里是够用的，别被「我不配」劝退。",
      "会有贵人出现，很可能是一个比你资深的人。",
      "转型或换方向是可行的，你的可迁移能力比想象中强。",
      "面试或考核会顺利，临场发挥是你的加分项。",
      "加薪或晋升有希望，但需要你先提出来。",
      "手上这个项目能做成，关键在前期把需求对齐。",
      "你在团队里的位置会变重要，接住它。",
      "适合开始一个副业或小尝试，成本可控。",
      "之前的付出会在这个阶段回本。",
      "会有人主动给你机会，认真对待。",
      "你的方案思路是对的，坚持推下去。",
      "这次变动对你有利，哪怕过程有点折腾。",
      "现在的大环境不太支持冒进，先稳住手头的事。",
      "有人在含糊其辞，重要的条件一定要落到白纸黑字。",
      "你低估了这件事的难度，重新评估一下时间和精力。",
      "这次竞争会比较激烈，提前准备备选方案。",
      "你的努力可能没落在关键点上，先确认对方真正要什么。",
      "团队里有沟通不畅或责任不清的问题，保护好自己。",
      "跳槽的时机还差一点，先把手上的事收尾。",
      "承诺的回报可能会打折，别只凭口头承诺做决定。",
      "你在硬撑一个并不适合你的方向，允许自己调整。",
      "会有一次挫折，但它暴露的是流程问题，不是你不行。",
      "别把所有赌注压在一个机会上。",
      "有人在推卸责任，把记录留好。",
      "短期内进展会比较慢，耐心比冲劲更重要。",
      "你的方案还需要再打磨，现在提交容易被退回。",
      "这个环境的天花板可能比你预期低，值得往外看看。",
      "会有一段疲惫期，先保证休息，别做重大决定。"
    ]
  },

  study: {
    label: "Study", icon: "📚",
    keys: [
      "study",
      "exam",
      "test",
      "grade",
      "grades",
      "score",
      "school",
      "college",
      "university",
      "class",
      "course",
      "homework",
      "thesis",
      "paper",
      "graduate",
      "graduation",
      "apply",
      "application",
      "admission",
      "scholarship",
      "professor",
      "dissertation",
      "semester",
      "quiz",
      "finals",
      "revision",
      "revise",
      "major",
      "degree",
      "campus",
      "student",
      "学习",
      "学业",
      "考试",
      "成绩",
      "分数",
      "考研",
      "高考",
      "中考",
      "期末",
      "期中",
      "论文",
      "毕业",
      "答辩",
      "申请",
      "录取",
      "保研",
      "留学",
      "四六级",
      "雅思",
      "托福",
      "证书",
      "考公",
      "公务员",
      "编制",
      "作业",
      "课程",
      "专业",
      "导师",
      "竞赛",
      "成绩单",
      "刷题",
      "复习",
      "补考",
      "挂科",
      "升学",
      "读研"
    ],
    en: [
      "You will pass. {Your foundation} is steadier than your nerves are telling you.",
      "Send the application. {The programme} is more interested in your direction than your polish.",
      "Keep the current method. {What you are doing} is working — it just has not shown up in a grade yet.",
      "Ask the question in class. {The thing everyone else is confused about} is exactly what you should raise.",
      "Study the past papers, not the textbook. {The pattern in the questions} is the real syllabus.",
      "Take the harder elective. {This one} will be the course you actually remember.",
      "Protect two hours each morning. {Consistent early work} will beat any all-nighter.",
      "Email the professor. {That office hour} is the single highest-value hour of your week.",
      "Trust the slow subject. {The one that feels hardest now} is the one building your range.",
      "Yes to the exchange or the competition. {The application cost} is far smaller than the regret.",
      "Change the method before you change the goal. {How you are revising} is the problem, not the subject.",
      "Cut the target in half. {The plan you wrote} is admirable and unlivable.",
      "The weak chapter is still weak. {Chapter you have been avoiding} is where the marks are hidden.",
      "Turn the phone off for one hour. {Your attention} is the resource that is actually failing.",
      "Do not compare timelines. {Someone else's progress} is not data about your ability.",
      "Start tonight, imperfectly. {The version you keep planning} will never be started.",
      "Prepare a backup path. {This first choice} is competitive, and you should not be holding only one door.",
      "Sleep before you revise once more. {The last hour of cramming} is costing you more than it adds.",
      "Ask for help sooner. {Struggling quietly} has stopped being noble about three weeks ago.",
      "It is not too late — but it is this week. {Starting now} is the whole difference."
    ],
    zh: [
      "会考好。你的基础比你以为的扎实，正常发挥就行。",
      "这次申请或考试有希望，关键是别在最后阶段松劲。",
      "你选的方向是对的，学下去会有回报。",
      "会遇到愿意帮你的老师或同学，主动去问。",
      "短期突击是有效的，但要抓重点而不是全面铺开。",
      "成绩会达到预期，甚至略微超出。",
      "适合挑战一个更难的目标，你现在够得着。",
      "之前卡住的地方会突然通，别放弃那道题。",
      "录取或通过的概率偏高，把材料准备扎实。",
      "你的努力是有效努力，不用怀疑方法。",
      "会有一次让你信心大增的成绩。",
      "论文或项目的方向可以定下来了，别再来回换。",
      "复习节奏调整一下就能提分，重点是错题。",
      "你担心的那门课，其实没那么难。",
      "会拿到一个不错的机会（竞赛、交流、实习），接住它。",
      "坚持下去，这次的结果会证明你的选择没错。",
      "现在的学习效率不高，换一种方法比硬扛更有效。",
      "你有点被「假努力」困住了，先停下来复盘。",
      "这次考试有风险，重点章节还没真正吃透。",
      "注意力被别的事分散了，先处理掉那个干扰源。",
      "目标定得太高了，拆成小步更容易推进。",
      "临场可能出状况，提前做模拟比多背一遍更有用。",
      "别指望运气，这门课需要实打实的时间投入。",
      "你选的这个方向可能并不适合你，值得重新想。",
      "申请结果存在不确定性，同时准备备选路径。",
      "拖延已经在影响结果了，今天就开始最小的一步。",
      "会有一次不理想的成绩，但它指出的是薄弱环节。",
      "你在跟别人比较，这正在消耗你。回到自己的节奏。",
      "信息收集得不够，做决定前多问几个人。",
      "短期内压力偏大，注意身体，别熬垮。",
      "这个任务比你想的花时间，尽早开始。",
      "结果可能延迟公布，别在等待里空耗。"
    ]
  },

  money: {
    label: "Money", icon: "💰",
    keys: [
      "money",
      "cash",
      "salary",
      "income",
      "save",
      "savings",
      "spend",
      "spending",
      "budget",
      "invest",
      "investment",
      "stock",
      "stocks",
      "fund",
      "debt",
      "loan",
      "borrow",
      "lend",
      "rich",
      "poor",
      "expensive",
      "cheap",
      "buy",
      "purchase",
      "afford",
      "bonus",
      "refund",
      "pay",
      "paid",
      "cost",
      "price",
      "rent",
      "bills",
      "钱",
      "财",
      "财运",
      "收入",
      "工资",
      "薪",
      "存款",
      "存钱",
      "攒钱",
      "理财",
      "投资",
      "基金",
      "股票",
      "赚",
      "亏",
      "花销",
      "花费",
      "预算",
      "借钱",
      "还钱",
      "贷款",
      "买房",
      "买车",
      "消费",
      "购物",
      "报销",
      "奖金",
      "红包",
      "负债",
      "信用卡",
      "省钱",
      "价格",
      "费用"
    ],
    en: [
      "Buy it. {This purchase} will quietly pay for itself within the year.",
      "Start with the boring account. {An automatic transfer on payday} beats every budgeting app.",
      "Yes to the raise conversation. {The number you had in mind} is lower than what is available.",
      "Say yes to the small side income. {The modest start} is the part that compounds.",
      "Hold the position. {Your patience} is being paid for, just not on your schedule.",
      "Ask for the invoice to be itemised. {Something in the total} does not add up.",
      "Spend on the tool, not the treat. {The thing that saves you time} is the better buy this month.",
      "Lend it, but write the date. {A clear deadline} protects the friendship more than the money.",
      "Keep the current pace. {Your quiet consistency} is working faster than you realise.",
      "Learn the skill that bills. {This one} has a price tag attached to it already.",
      "Wait one week. {The urgency you feel} was manufactured by the listing, not by need.",
      "Read the terms again. {One clause} is doing more work than you think.",
      "Do not lend this one. {The amount} is more than the relationship can carry.",
      "Check the number before you agree. {The quoted figure} is not the final figure.",
      "Stop the subscription sweep. {Three small monthly charges} are quietly eating a real amount.",
      "Do not chase it. {This opportunity} has the shape of a loss with good manners.",
      "Set the floor. {A minimum price} will change how people treat your work.",
      "Delay the upgrade. {What you already own} is fully capable for another year.",
      "Write it down for a month. {Where the money actually goes} will surprise you twice.",
      "Say no to the favour. {Being generous with money} is not the same as being generous with yourself."
    ],
    zh: [
      "财运会好转，会有一笔之前没预期的收入。",
      "现在适合稳健积累，不适合赌一把。",
      "你之前的一笔投入会开始回本。",
      "谈钱的时候可以直接一点，这次你占理。",
      "会有人还你钱，或者给你应得的补偿。",
      "这笔花销是值得的，它会在以后帮到你。",
      "适合开始记账或存钱，效果比你想的明显。",
      "你的报价可以再高一档，别低估自己的价值。",
      "会有额外进账的机会，但需要你主动接。",
      "财务状况在往好的方向走，保持现在的节奏。",
      "借钱给别人这件事可以答应，但要把期限说清楚。",
      "适合学一个能变现的技能，回报在中长期。",
      "你担心的那笔钱，最后不会亏太多。",
      "会有一笔小惊喜：退款、红包或者报销。",
      "现在开始攒钱，三个月后能看到明显变化。",
      "这次选择偏保守是对的，稳比快重要。",
      "最近容易超支，先看一眼账再决定买不买。",
      "有一笔支出会比预期高，记得留出余地。",
      "别碰高风险的东西，这次的运气不在赌上。",
      "有人在钱的事上不够透明，问清楚再合作。",
      "借出去的钱短期收不回来，量力而行。",
      "你的收入和付出不太匹配，值得重新谈。",
      "会有一个看起来很划算的坑，多问一句「凭什么」。",
      "冲动消费会后悔，先放购物车等一天。",
      "这笔投资短期会亏，做好心理准备。",
      "别为了面子花钱，这次的面子不值那个价。",
      "财务状况需要主动整理，拖着只会更乱。",
      "有人可能占你便宜，把账目记清楚。",
      "现在不适合扩张或加杠杆，先守住本金。",
      "会有一笔意外开销，应急金该留了。",
      "报酬可能被压价，提前把标准说好。",
      "你对自己时间的定价太低了。"
    ]
  },

  social: {
    label: "People", icon: "🤝",
    keys: [
      "friend",
      "friends",
      "friendship",
      "family",
      "mom",
      "mum",
      "dad",
      "mother",
      "father",
      "parents",
      "roommate",
      "classmate",
      "sibling",
      "brother",
      "sister",
      "neighbour",
      "neighbor",
      "social",
      "argument",
      "fight",
      "apologise",
      "apologize",
      "forgive",
      "trust",
      "gossip",
      "lonely",
      "party",
      "group",
      "colleague",
      "relationship with",
      "awkward",
      "人际",
      "朋友",
      "友情",
      "闺蜜",
      "兄弟",
      "同学",
      "室友",
      "家人",
      "父母",
      "妈妈",
      "爸爸",
      "家庭",
      "亲戚",
      "社交",
      "关系",
      "圈子",
      "被孤立",
      "排挤",
      "误会",
      "矛盾",
      "吵架",
      "冷战",
      "和好",
      "原谅",
      "信任",
      "团队",
      "合作",
      "人缘",
      "同班",
      "友谊"
    ],
    en: [
      "Message first. {The silence between you} is shyness on both sides, not a verdict.",
      "Say the awkward thing kindly. {This conversation} will be shorter and warmer than you fear.",
      "Accept the invitation. {The person who invited you} specifically wanted you there.",
      "Let them explain. {What looked like neglect} was probably just a bad month.",
      "Reach out to the old friend. {The years in between} matter less than you think.",
      "Keep this one close. {This friendship} is one of the rare ones that survives distance.",
      "Be the one who apologises first. {Being right} is worth less than being together.",
      "Ask the second question. {Curiosity} is the whole trick to being liked.",
      "Say no without the essay. {A plain, warm refusal} will be respected more than a long excuse.",
      "Let the group find its shape. {The awkward phase} passes faster than anyone admits.",
      "Let this one cool. {This relationship} is being held together mostly by habit.",
      "Do not explain yourself again. {The person who keeps misunderstanding you} has already decided.",
      "Set the boundary and expect a reaction. {Saying no} will reveal who was only ever there for the yes.",
      "Keep it off the group chat. {This problem} belongs in one private conversation.",
      "Stop over-giving. {Your constant availability} is why nobody notices the effort.",
      "It is not your job to fix it. {The family argument} has older roots than you.",
      "Distance is allowed. {Choosing quiet} is not the same as losing the friendship.",
      "Watch what they do after you say it. {The reaction} is the information you were missing.",
      "Do not take the comparison bait. {Being measured against someone else} is a game with no prize.",
      "Let one thing go. {The grudge you are carrying} costs you more than it costs them."
    ],
    zh: [
      "这段关系会缓和，主动打个招呼就有转机。",
      "有人其实站在你这边，只是没说出来。",
      "适合把心里的话说出来，对方接得住。",
      "会认识一个聊得来的人。",
      "家人最终会理解你的选择，给他们一点时间。",
      "这次的误会能解开，关键是有一个人先开口。",
      "你在圈子里的口碑比你以为的好。",
      "适合主动联系一个很久没见的朋友。",
      "团队里会有人帮你说话。",
      "这段友谊经得起时间，值得维护。",
      "你的善意会被记住，只是回报来得慢。",
      "会有一次让你觉得被真正理解的对话。",
      "拒绝别人这件事，这次可以坦然一点。",
      "你担心的那个矛盾，其实没那么严重。",
      "会有人主动向你示好。",
      "保持现在的真诚，你的关系网会越来越稳。",
      "有人在背后说闲话，不用解释太多，时间会证明。",
      "这段关系里存在不对等，留意自己的感受。",
      "有人在利用你的好说话，学着设边界。",
      "这次沟通容易产生误解，重要的事最好当面说。",
      "你正在勉强自己迎合别人，这会很累。",
      "家人那边还会有分歧，别指望一次谈成。",
      "有个朋友的关系在变淡，顺其自然就好。",
      "别把秘密告诉不够熟的人。",
      "会听到让你不舒服的话，先别急着反击。",
      "这段关系需要一次坦白，不然会一直别扭。",
      "你在意的那个人，最近没把注意力放在你身上。",
      "团队里可能有小团体，保持中立更安全。",
      "你付出得太多，而对方已经习惯了。",
      "这次聚会可能会让你失望，去不去都行。",
      "有人在拿你们做比较，别接这个茬。",
      "需要一次断舍离，有些关系该降温了。"
    ]
  },

  health: {
    label: "Health", icon: "🌿",
    keys: [
      "health",
      "healthy",
      "sick",
      "ill",
      "cold",
      "fever",
      "headache",
      "migraine",
      "pain",
      "sleep",
      "insomnia",
      "tired",
      "exhausted",
      "energy",
      "diet",
      "weight",
      "exercise",
      "workout",
      "gym",
      "stress",
      "stressed",
      "anxious",
      "anxiety",
      "depressed",
      "mood",
      "doctor",
      "hospital",
      "checkup",
      "rest",
      "burnout",
      "recover",
      "recovery",
      "body",
      "健康",
      "身体",
      "生病",
      "感冒",
      "发烧",
      "疼",
      "痛",
      "失眠",
      "睡眠",
      "熬夜",
      "累",
      "疲劳",
      "精力",
      "体力",
      "免疫",
      "过敏",
      "胃",
      "头疼",
      "头痛",
      "眼睛",
      "腰",
      "颈椎",
      "减肥",
      "体重",
      "运动",
      "锻炼",
      "作息",
      "压力",
      "焦虑",
      "情绪",
      "心理",
      "医生",
      "体检",
      "医院",
      "恢复",
      "养生"
    ],
    en: [
      "Sleep is the whole treatment. {One week of real rest} will do what nothing else has.",
      "Start with ten minutes. {A walk you will actually repeat} beats a plan you will abandon.",
      "You are tired, not ill. {The fatigue} is a message about your schedule, not your body.",
      "Go for the check-up anyway. {The reassurance} is worth the appointment on its own.",
      "Eat something warm and cooked. {Real meals} have been missing from your week.",
      "Cut caffeine after two. {That single change} will hand you back your evenings.",
      "Say the feeling out loud to someone. {Naming it} takes away about a third of its weight.",
      "Keep going with the routine. {The consistency} is starting to show in how you carry yourself.",
      "Take the slow morning. {The pressure you feel} is external and can wait until noon.",
      "This is a good week to start. {Your energy} is coming back — use it gently.",
      "Stop pushing through. {The signal your body keeps sending} is the one to listen to now.",
      "Book the appointment. {Uncertainty} is costing you more sleep than the answer would.",
      "Cut the plan in half. {The routine you designed} was built for a version of you with more time.",
      "The problem is cumulative. {Weeks of short nights} do not get fixed by one good weekend.",
      "Put the phone down an hour earlier. {The scrolling} is where your rest is going.",
      "Do not make the big decision this week. {Your reserves} are too low to judge clearly.",
      "Tell someone how tired you are. {Hiding it} has become its own kind of work.",
      "Move your body, gently. {The stiffness} is asking for motion, not for more rest.",
      "Lower your own expectations first. {The standard you are holding} is the stressor.",
      "Give recovery more time than feels reasonable. {Healing} is running on its own clock."
    ],
    zh: [
      "身体会好转，规律作息比什么都管用。",
      "现在开始调整还来得及，效果会很快显现。",
      "你的疲劳是休息不够，不是生病，睡够就好。",
      "这次的检查结果会让人安心。",
      "适合开始一项能坚持的运动，轻量的就行。",
      "情绪状态在回升，给自己一点肯定。",
      "会找到适合你的作息节奏。",
      "你担心的那个症状大概率不严重，但还是去查一下更放心。",
      "恢复力比你想象的好，别太焦虑。",
      "饮食调整一下，精力会有明显变化。",
      "适合早睡，这一条能解决你一半的问题。",
      "压力源正在减弱，你会慢慢松下来。",
      "会有人提醒你注意身体，听进去。",
      "你的自律正在起效，继续保持。",
      "放松这件事，你做得比你以为的好。",
      "会有一段状态特别好的时期，抓住它做重要的事。",
      "身体在给你信号了，别再硬扛。",
      "熬夜的账迟早要还，这两周尽量早睡。",
      "建议去做一次检查，别靠猜。",
      "你的疲劳是累积的，需要真正的休息而不是硬撑。",
      "情绪正在消耗你的身体，找人聊聊。",
      "运动计划定得太狠了，容易放弃，先减半。",
      "最近免疫力偏低，注意保暖和饮食。",
      "有个小毛病拖得有点久了，去处理掉。",
      "你在用刷手机和外卖填补疲惫，这解决不了问题。",
      "压力已经影响到睡眠了，认真对待。",
      "别靠咖啡因撑，那是在透支。",
      "这次恢复会比预期慢，给自己更多耐心。",
      "焦虑放大了你对身体的感受，先放松再看。",
      "久坐的问题需要现在就改。",
      "会有一段状态低落的时期，允许自己慢一点。",
      "别人给你的健康建议，这次值得听。"
    ]
  },

  general: {
    label: "General", icon: "✨",
    keys: [

    ],
    en: [
      "Yes. {The thing you are asking about} is more possible than it looked last week.",
      "Start small and start today. {The first step} is the only one that is actually required.",
      "The timing is good. {What you are hesitating over} is a hesitation, not a warning.",
      "Say yes. {This particular door} will not stay open indefinitely.",
      "Trust your first instinct. {The answer you already had} was the right one.",
      "Ask one more person. {The perspective you are missing} is closer than you think.",
      "Do the version that scares you slightly. {That specific choice} is the one that grows.",
      "Let it be imperfect. {Finished and flawed} beats polished and imaginary.",
      "Give it a season. {The result you want} is forming, just below the surface.",
      "Take the risk. {The downside} is smaller and more survivable than your imagination says.",
      "Wait. {This is not the week} to decide something this size.",
      "You are missing a piece of information. {The thing nobody has told you yet} is the one that matters.",
      "Lower the stakes. {Your plan} assumes everything goes right at once.",
      "Not this one. {The pull you feel} is curiosity wearing the costume of certainty.",
      "Change the approach, not the goal. {The method} is what has stopped working.",
      "Do not decide out of tiredness. {How you feel tonight} is not how you will feel on Sunday.",
      "Protect your energy first. {This question} can wait until you have slept properly.",
      "Look at what you are avoiding. {The part you keep skipping} is the actual answer.",
      "Stop asking everyone else. {The opinions} are now just noise around your own.",
      "Say no for now. {A later yes} is still available, and a rushed yes is not."
    ],
    zh: [
      "可以。这件事的阻力比你感觉的小。",
      "会成，但需要你先迈出第一步。",
      "时机是好的，别把犹豫当成谨慎。",
      "你担心的最坏情况，大概率不会发生。",
      "答案偏向肯定，你的直觉是对的。",
      "会有贵人或者转机出现，留意身边的人。",
      "现在适合行动，等待只会让成本变高。",
      "你能做成这件事，准备已经足够了。",
      "结果会比你预期的好一些。",
      "值得一试。即使不完美，收获也是你的。",
      "会有好消息传来，保持开放。",
      "你已经在正确的路上，继续走就行。",
      "可以答应，这次的机会对你有利。",
      "放下过度思考，答案其实很简单。",
      "会有一次意外的顺利。",
      "你比自己以为的更有底气。",
      "现在开始不算晚。",
      "这件事的走向是向上的，耐心一点。",
      "你需要的资源其实已经在你手上了。",
      "大胆一点，退路没有你想的那么必要。",
      "现在不是好时机，先缓一缓。",
      "这件事还有你没看到的信息，别急着定。",
      "结果可能不如预期，做好备选方案。",
      "你在勉强一件事，停下来问问自己为什么。",
      "会有阻力，但不是死路，换个方法再试。",
      "别把希望全押在这一件事上。",
      "有人在影响你的判断，听听自己怎么想。",
      "现在下决定容易后悔，再等一周。",
      "你忽略了某个明显的信号，回头看看。",
      "这件事的代价比你想的大，重新算一遍。",
      "短期内不会有明确答案，先接受这个状态。",
      "你在重复一个已经试过的做法。",
      "需要放下点什么，才走得动。",
      "会有一点失望，但它不影响大局。",
      "别急着答应，先看清条件。",
      "你太在意别人的看法了。",
      "这次靠运气不够，得靠准备。",
      "有件事你一直没处理，它正在拖住你。",
      "慢一点。快了容易出错。",
      "答案偏向「不」，但不是永远不。"
    ]
  }
};


var TOPIC_ORDER = ['love','career','study','money','social','health','general'];

/* 是否含中文 */
function hasCJK(s){ return /[\u4e00-\u9fff]/.test(s); }

/* ---------------------------------------------------------
   问题 → 话题
   英文按「整词」匹配（支持简单复数），中文按「子串」匹配
   --------------------------------------------------------- */
function detectTopic(q){
  if (!q) return { topic: 'general', hits: 0 };

  var lower = q.toLowerCase();
  var tokens = lower.replace(/[^a-z0-9']+/g, ' ').trim().split(' ').filter(Boolean);
  var tokenSet = {};
  for (var t = 0; t < tokens.length; t++) tokenSet[tokens[t]] = 1;

  function matchEn(w){
    return !!(tokenSet[w] || tokenSet[w + 's'] || tokenSet[w + 'es']);
  }

  var best = 'general', bestScore = 0, bestHits = 0;
  for (var i = 0; i < TOPIC_ORDER.length; i++){
    var key = TOPIC_ORDER[i];
    if (key === 'general') continue;
    var words = TOPICS[key].keys, score = 0, hits = 0;
    for (var j = 0; j < words.length; j++){
      var w = words[j], hit = false, cjk = hasCJK(w);
      if (cjk)            hit = q.indexOf(w) >= 0;
      else if (w.indexOf(' ') >= 0) hit = lower.indexOf(w) >= 0;
      else                hit = matchEn(w);
      if (hit){ score += w.length * (cjk ? 2 : 1); hits++; }
    }
    if (score > bestScore){ bestScore = score; best = key; bestHits = hits; }
  }
  return { topic: best, hits: bestHits };
}

/* ---------------------------------------------------------
   按问题语言取答案
   --------------------------------------------------------- */
function pickAnswer(topicKey, lang){
  var t = TOPICS[topicKey] || TOPICS.general;
  var bank = (lang === 'zh' && t.zh.length) ? t.zh : t.en;
  return bank[Math.floor(Math.random() * bank.length)];
}
